### ISSUE TITLE
Slight issue

### ISSUE THREAD

**Issue by stickypages** [ua-parser/uap-php#14]
Just having a small issue with the 'cache', it is conflicting with my framework cache system. Perhaps a new 'nameing' scheme could be helpful.

**Comment by JustBlackBird** [comment]
It does not seem that the parser's API provides any public method/propery with `cache` name. Are you've opened issue in the right place? :smiley:

**Comment by stickypages** [comment]
ARG!, Sorry! My Bad.... first for everything. *IGNORE*
