### ISSUE TITLE
Differentiating from WebView mobile chrome and real Mobile Chrome

### ISSUE THREAD

**Issue by bwaters** [ua-parser/uap-php#15]
Is there anyway for uap-php to tell the difference between WebView in an Android App and the Chrome Mobile browser.  https://developer.chrome.com/multidevice/user-agent

Looks like if it has a Version/x.x then it is webview ie..

Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG-SM-G870A Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36

Vs a real chrome ua like this one:

Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG-SM-G900A Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36

**Comment by lstrojny** [comment]
Moved to https://github.com/ua-parser/uap-core/issues/38
