### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by mzgol** [ua-parser/uap-php#17]
`uap-core` now [supports Microsoft Edge](https://github.com/ua-parser/uap-core/commit/57b37b6524f91434570e6e049c5bf9b485aed9a6) (it was earlier recognized as IE12, erroneously). Could you update the git submodule so that `uap-php` has this change as well?

**Comment by lstrojny** [comment]
Done!

**Comment by mzgol** [comment]
Thanks! Do you plan a new release soon?

**Comment by JustBlackBird** [comment]
It seems that the updated version is already released as `v3.4.3`

**Comment by lstrojny** [comment]
Yep, v3.4.3 is released and has the changes

**Comment by mzgol** [comment]
Ahh, thanks again then. :)

**Comment by Abhinav1217** [comment]
Hi, Sorry to open it again but

**Comment by mzgol** [comment]
@Abhinav1217 it seems you have an outdated version, it should work in 3.4.3 as stated above.

**Comment by Abhinav1217** [comment]
I used `ua-parser/uap-php` in `composer init` automated install.

**Comment by Abhinav1217** [comment]
I re downloaded from composer specifically for 3.4.3 It is still detecting Edge as chrome.
I even checked http://uaparser.dmolsen.com/. Chrome.
