### ISSUE TITLE
Convert to json file is not implemented

### ISSUE THREAD

**Issue by prakashrd** [ua-parser/uap-php#18]
Hi,

The option to convert from yaml to json is not implemented as stated. Actually it does read the yaml file and writes to a PHP file named 'resources.php'. 

Also it will be nice to have option to specify the destination file.

Cheers,
Jai

**Comment by lstrojny** [comment]
Sounds good. Do you mind opening a pull request?

**Comment by lstrojny** [comment]
Closing
