### ISSUE TITLE
Microsoft Edge detecting as Chrome .

### ISSUE THREAD

**Issue by Abhinav1217** [ua-parser/uap-php#19]
Hi, 
Sorry to open similar issue again but I updated my system to windows 10, and Now on edge browser, 
`print $result->ua->family;` outputs as Chrome instead of Edge. 

This is the output I am getting on your example.
```
========================================
Edge:
========================================

ua-parser-php Test

ua-parser-php is the PHP library for the ua-parser project. Please use this page to test your browser. ua-parser-php was developed to help support my Detector project.
  ua->family: Chrome
  ua->major: 42
  ua->minor: 0
  ua->patch: 2311
  ua->toString: Chrome 42.0.2311
  ua->toVersionString: 42.0.2311
  os->family: Windows
  os->major: 
  os->minor: 
  os->patch: 
  os->patch_minor: 
  os->toString: Windows
  os->toVersionString: 
  device->family: Other
  toFullString: Chrome 42.0.2311/Windows
  uaOriginal: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
``` 

As a temp fix on my website, I am searching for "Edge" using regex in `$result->originalUserAgent;`
But It would be nice to get `Family` as `Edge`.

**Update :** 
I re downloaded from composer specifically for 3.4.3 It is still detecting Edge as chrome.
I even checked http://uaparser.dmolsen.com/. Chrome.

**Comment by secondtruth** [comment]
I think this problem should be reported at [ua-parser/uap-core](https://github.com/ua-parser/uap-core).
