### ISSUE TITLE
Installation without composer

### ISSUE THREAD

**Issue by Pierroda** [ua-parser/uap-php#24]
Dears,

I can't use the composer tool on my website.

Is there another way to install ua-parser ?

Thanks in advance.

**Comment by lstrojny** [comment]
No, there is no other way then to install it via composer. If you don’t use composer yet, probably a good time to start using it

**Comment by Pierroda** [comment]
Yes it is, but my Web hoster don't enable me to use composer.

Pierre Haenen
Rue de la Concorde 49 - 4800 Verviers
0032 496 92 81 12

**Comment by lstrojny** [comment]
@Pierroda has nothing to do with your webhoster. You can run composer on a different machine before you actually deploy your app.

**Comment by Pierroda** [comment]
OK, thus I'll try to do so ! Thanks for your help.

*Pierre Haenen*
Rue de la Concorde, 49 - 4800 Verviers
0032 496 92 81 12

2015-12-07 19:04 GMT+01:00 Lars Strojny <notifications@github.com>:
