### ISSUE TITLE
"Mi 4i" is not correctly detected as xiaomi

### ISSUE THREAD

**Issue by fajarnugraha** [ua-parser/uap-php#29]
Chrome Beta on Xiaomi Mi 4i has the following user agent string:

``
Mozilla/5.0 (Linux; Android 5.0.2; Mi 4i Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.36 Mobile Safari/537.36
``

Installing the default version with composer (``require ua-parser/uap-php``) identifies device brand as ``Generic_Android``, where it should be ``XiaoMi``

Editing https://github.com/ua-parser/uap-php/blob/master/resources/regexes.php#L4451 , changing it to ``      'regex' => '; *((Mi|MI|HM|MI-ONE|Redmi)[ -](NOTE |Note )?[^;/]*) Build/',`` (adding ``Mi``) makes it detect the brand correctly

**Comment by lstrojny** [comment]
This is just the PHP binding, not the underlying data itself. Can you report your bug to https://github.com/ua-parser/uap-core?

Thank you!
