### ISSUE TITLE
Performance improvement when placing most common browser/os/device on top of the regexes list

### ISSUE THREAD

**Issue by vahemark** [ua-parser/uap-php#31]
There would be noticeably faster parsing when the browsers and operating systems which have the most market share are placed on top of the regexes list. Due to looping through the list, the more chances we have a match the sooner we break the loop and return the result.

This issue also applies to other languages and, thus, is not limited to PHP only. Perhaps this is not the right place to create this issue, but you can move it to the proper repository.

**Comment by ThaDafinser** [comment]
Core/regex files are here https://github.com/ua-parser/uap-core

**Comment by vahemark** [comment]
thanks
