### ISSUE TITLE
Using Chrome on mac os comes out as 'Other'

### ISSUE THREAD

**Issue by forceedge01** [ua-parser/uap-php#32]
We've just found out this issue. At the moment if you use Chrome on mac os x the device recorded by the ua-parser comes out as Other with no branch or model.

This is happening on v3.4.5.

**Comment by lstrojny** [comment]
As this is just the PHP implementation of ua-parser/uap-core, would you mind reporting the bug here? https://github.com/ua-parser/uap-core
