### ISSUE TITLE
Doesn't recognize SRWare Iron

### ISSUE THREAD

**Issue by therentabrain** [ua-parser/uap-php#35]
I know this is a fairly obscure choice, but I've got all my clients into SRWare Iron (Portable).  It's being recognized as Chrome.  The two most recent versions (51.x and 52.x, the current one) have changed how their ua string is formatted.

Here's my current one:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2750.0 Iron Safari/537.36

There is no longer a slash and a version number after "Iron" in the string.

I'm not sure where to post this concern, so I'm starting here.  Long time happy user, first time troubleshooter.  Thanks for any advice and for the fabulous tool.

**Comment by commenthol** [comment]
Could you please open this issue in uap-core? Thanks.
