### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by esurov** [ua-parser/uap-php#36]
Hi!

Does uap-php support PHP 7.1. I noticed there's no such version in travis config. I also tried to run unit tests and 3 of them failed:

genote:vena gene$ phpunit --verbose vendor/ua-parser/uap-php/
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.1
Configuration: /Users/gene/Work/ssp/phpunit.xml

.EEE...................S                                          24 / 24 (100%)

Time: 1.03 seconds, Memory: 26.00MB

There were 3 errors:

1) UAParser\ParserTest::testDeviceParsing
ArgumentCountError: Too few arguments to function UAParser\ParserTest::testDeviceParsing(), 0 passed and exactly 9 expected

/Users/gene/Work/ssp/vendor/ua-parser/uap-php/tests/ParserTest.php:79

2) UAParser\ParserTest::testOperatingSystemParsing
ArgumentCountError: Too few arguments to function UAParser\ParserTest::testOperatingSystemParsing(), 0 passed and exactly 7 expected

/Users/gene/Work/ssp/vendor/ua-parser/uap-php/tests/ParserTest.php:89

3) UAParser\ParserTest::testUserAgentParsing
ArgumentCountError: Too few arguments to function UAParser\ParserTest::testUserAgentParsing(), 0 passed and exactly 6 expected

/Users/gene/Work/ssp/vendor/ua-parser/uap-php/tests/ParserTest.php:101

--

There was 1 skipped test:

1) UAParser\Util\Logfile\ApacheCommonLogFormatReaderTest::testReadingFile
Try with your own log file

/Users/gene/Work/ssp/vendor/ua-parser/uap-php/tests/Util/Logfile/AbstractReaderTest.php:55

ERRORS!
Tests: 24, Assertions: 46, Errors: 3, Skipped: 1.

**Comment by swen100** [comment]
UAParser runs fine on PHP 7.2. So it runs on PHP 7.1, too.
