### ISSUE TITLE
Make symfony not a required dependency

### ISSUE THREAD

**Issue by oligriffiths** [ua-parser/uap-php#43]
Hi

Why is symfony a required dependency? This should really be a "suggests" than a require, as the docs say you can use this stand alone without the CLI.

Can this be removed please?

Thanks

**Comment by Josniii** [comment]
This also means that you can't really use the parser with OctoberCMS as things are right now, as the symfony/filesystem dependency breaks things.

**Comment by oligriffiths** [comment]
Sure thing

**Comment by lstrojny** [comment]
Merged now
