### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by JustBlackBird** [ua-parser/uap-php#5]
The current repository does not exist on `packagist.org`. At the `tobie/ua-parser` package contains files for other languages which are useless for a PHP application.

I believe `ua-parser/ua-parser` package from this repository should be published.

**Comment by lstrojny** [comment]
Finally published as https://packagist.org/packages/ua-parser/uap-php

**Comment by JustBlackBird** [comment]
@lstrojny Thank you!
