### ISSUE TITLE
Added typehint to Parser breaks Symfony compiled class

### ISSUE THREAD

**Issue by progrupa** [ua-parser/uap-php#60]
After a recent update I get this error:
Compile Error: Declaration of Parser_9383176::parse($userAgent, array $jsParseBits = Array) must be compatible with UAParser\Parser::parse(string $userAgent, array $jsParseBits = Array): UAParser\Result\Client

**Comment by lstrojny** [comment]
This looks like a generated proxy, regenerating the proxy on your side will fix the issue. 

If I misunderstood you, please reopen the issue.
