### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by hisorange** [ua-parser/uap-php#61]
Hey there!

My question is that the package versioned by semver or a simple stepping?

I wouldn't open an issue for a question like this :D But the release 3.9.8 introduced a breaking change as a patch version and caused issues with users on PHP 7.1 and below.

This was on purpose and I wrongfully assumed semantic versioning or this slipped through the release process? :D

Anyways, thanks for the answer in advance and keep up the good work!

**Comment by lstrojny** [comment]
Indeed, 3.9.8 would have warranted at least a 3.10, if not a 4.0. Unfortunately it’s too late now but it was a mistake to not bump.
